#!/bin/bash
dir=$(pwd)
logdir=/software/log/

start() {
	echo start..
	if [ -f provider-hystrix.pid ];then
		echo 系统已启动，不能重复启动。如果确实没有重复启动，请删除provider-hystrix.pid文件后在启动
		return
	fi	

	if [ ! -d $logdir/log-provider-hystrix ];then
		mkdir $logdir/log-provider-hystrix
	fi
	
	java -jar provider-hystrix-0.0.1-SNAPSHOT.jar >> $logdir/log-provider-hystrix/stdout.log &
	echo $!>provider-hystrix.pid
	echo started
}


stop() {
	if [ ! -f provider-hystrix.pid ]; then
		return
	fi
	
	local pid=$(cat provider-hystrix.pid)
	echo "pid:$pid"
	kill $pid
	rm provider-hystrix.pid
	
	local i=0
	while [ $i -lt 65 ]; do
		i=$((i+1))
		sleep 1
		if [ ! -z "$(ps ux | grep -v grep | grep $pid)"];then
			echo stopping...
		else
			break
		fi
	done
	
	echo Stopped.		
}

if [ $1 = start ]
then
	start
fi

if [ $1 = stop ]
then
	stop
fi