server: 
  port: 8003

mybatis: 
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations: 
    - "classpath:mybatis/mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: com.feifeishi.entity           		  # 别名类所在包

spring: 
  application: 
    name: provider                         					 #微服务的名字
  datasource: 
    driver-class-name: org.gjt.mm.mysql.Driver                # mysql驱动包      
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: "jdbc:mysql://111.229.127.200:3306/sod?useUnicode=true&characterEncoding=utf-8&useSSL=false"                    # 数据库名称
    username: root
    password: root	
    initialSize : 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j #配置监控统计拦截的filters 去掉后监控界面sql无法统计，‘wall’用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500
    druid:
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除. 
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-while-idle: true
      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
      #validationQuery参数必须设置为非空字符串
      test-on-return: false
      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
      #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
      validation-query: select 1
  banner:
    location:
      banner.txt

security:
  user:
    name: feifeishi  #鉴权账号
    password: 123456    #鉴权密码
  basic:
    enabled: true
    path: /admin    鉴权路径
management:
  port: 8089 #actuator暴露接口使用的端口，为了和api接口使用的端口进行分离
  context-path: /admin #actuator暴露接口的前缀
  security:
    enabled: true #actuator是否需要安全保证
    roles: SUPERUSER

eureka:
  client:
    service-url:
       #defaultZone: http://localhost:9001/eureka
      defaultZone: http://111.229.127.200:9001/eureka/,http://111.229.127.200:9002/eureka/,http://111.229.127.200:9003/eureka/
  instance:
    instance-id: provider-hystrix								  #自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址