server: 
  port: 8003

mybatis: 
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations: 
    - "classpath:mybatis/mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: com.feifeishi.entity           		  # 别名类所在包

spring: 
  application: 
    name: provider                         					 #微服务的名字
    
  datasource: 
    driver-class-name: org.gjt.mm.mysql.Driver                # mysql驱动包      
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: "jdbc:mysql://111.229.127.200:3306/sod?useUnicode=true&characterEncoding=utf-8&useSSL=false"                    # 数据库名称
    username: root
    password: root	
	filters: stat,wall,log4j #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
	initialSize: 2
	maxActive: 300
	maxWait: 60000
	timeBetweenEvictionRunsMillis: 60000
	minEvictableIdleTimeMillis: 300000
	validationQuery: SELECT 1
	testWhileIdle: true
	testOnBorrow: false
	testOnReturn: false
	poolPreparedStatements: false
	maxPoolPreparedStatementPerConnectionSize: 200

  banner:
    location:
      banner.txt
            
security:
  user:
    name: feifeishi  #鉴权账号
    password: 123456    #鉴权密码
  basic:
    enabled: true
    path: /admin    鉴权路径
management:
  port: 8089 #actuator暴露接口使用的端口，为了和api接口使用的端口进行分离
  context-path: /admin #actuator暴露接口的前缀
  security:
    enabled: true #actuator是否需要安全保证
    roles: SUPERUSER

eureka:
  client:
    service-url:
       #defaultZone: http://localhost:9001/eureka
      defaultZone: http://111.229.127.200:9001/eureka/,http://111.229.127.200:9002/eureka/,http://111.229.127.200:9003/eureka/
  instance:
    instance-id: provider-hystrix								  #自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址
 
